Algoritmo "parimpar"
// Disciplina   : Programação e Algorítimo
// Professor   : Cíntia Pinho
// Descrição   : descobre se um número é par ou impar
// Autor(a)    : Maria Luisa Amaral
// Data atual  : 22/05/21
Var

num: inteiro
par, impar: logico




Inicio

// Entrada

escreval ("Escreva um número:")
leia (num)

par <- (num mod 2)=0
impar <- (num mod 2)=1

escreval ("Par:", par)
escreval ("Impar:", impar)

//Saída


Fimalgoritmo